# Generated by Django 3.2.13 on 2022-10-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
